// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneticAnalyzers.Infrastructure.Persistence;

#nullable disable

namespace PhoneticAnalyzers.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneticAnalyzersDbContext))]
    [Migration("20251107184701_OptimizeMortgageSearchIndexes")]
    partial class OptimizeMortgageSearchIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.BeiderMorseVariant", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("BeiderMorseCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bm_code");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("PersonId", "BeiderMorseCode");

                    b.HasIndex("BeiderMorseCode")
                        .HasDatabaseName("ix_person_bm_code");

                    b.ToTable("person_bm", null, t =>
                        {
                            t.HasComment("Beider-Morse variants table partitioned by first_letter");
                        });
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternateDoubleMetaphone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dm_alternate");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county");

                    b.Property<int>("CountyId")
                        .HasColumnType("integer")
                        .HasColumnName("county_id");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("county_name");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<char>("Flag")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("flag");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("PartitionHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("dm_hash")
                        .HasComputedColumnSql("ABS(HASHTEXT(normalized_name)) % 64", true);

                    b.Property<string>("PrimaryDoubleMetaphone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dm_primary");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.HasIndex("AlternateDoubleMetaphone")
                        .HasDatabaseName("ix_person_dm_alternate")
                        .HasFilter("dm_alternate IS NOT NULL");

                    b.HasIndex("CountyId")
                        .HasDatabaseName("ix_person_county_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_external_id");

                    b.HasIndex("Flag")
                        .HasDatabaseName("ix_person_flag");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_person_normalized_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PrimaryDoubleMetaphone")
                        .HasDatabaseName("ix_person_dm_primary")
                        .HasFilter("dm_primary IS NOT NULL");

                    b.HasIndex("CountyId", "Flag")
                        .HasDatabaseName("ix_person_county_flag");

                    b.ToTable("person", null, t =>
                        {
                            t.HasComment("Person table partitioned by dm_hash for better performance");
                        });

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.BeiderMorseVariant", b =>
                {
                    b.HasOne("PhoneticAnalyzers.Domain.Entities.Person", null)
                        .WithMany("BeiderMorseVariants")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.Person", b =>
                {
                    b.Navigation("BeiderMorseVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
