// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneticAnalyzers.Infrastructure.Persistence;

#nullable disable

namespace PhoneticAnalyzers.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneticAnalyzersDbContext))]
    [Migration("20251108053143_AddMultilingualSearchEntitiesFixed")]
    partial class AddMultilingualSearchEntitiesFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.BeiderMorseVariant", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("BeiderMorseCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bm_code");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("PersonId", "BeiderMorseCode");

                    b.HasIndex("BeiderMorseCode")
                        .HasDatabaseName("ix_person_bm_code");

                    b.ToTable("person_bm", null, t =>
                        {
                            t.HasComment("Beider-Morse variants table partitioned by first_letter");
                        });
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.NameAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alias_type");

                    b.Property<string>("BeiderMorseCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bm_code");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DoubleMetaphoneCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dm_code");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_alias");

                    b.Property<long>("PersonNameId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_name_id");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("script");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeiderMorseCode")
                        .HasDatabaseName("ix_name_aliases_bm_code")
                        .HasFilter("bm_code IS NOT NULL");

                    b.HasIndex("DoubleMetaphoneCode")
                        .HasDatabaseName("ix_name_aliases_dm_code")
                        .HasFilter("dm_code IS NOT NULL");

                    b.HasIndex("NormalizedAlias")
                        .HasDatabaseName("ix_name_aliases_normalized_alias_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedAlias"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedAlias"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PersonNameId")
                        .HasDatabaseName("ix_name_aliases_person_name_id");

                    b.HasIndex("Locale", "AliasType")
                        .HasDatabaseName("ix_name_aliases_locale_type");

                    b.HasIndex("Source", "Confidence")
                        .HasDatabaseName("ix_name_aliases_source_confidence");

                    b.HasIndex("PersonNameId", "Alias", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_name_aliases_unique");

                    b.ToTable("name_aliases", (string)null);
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.NameAliasCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CachedAliases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cached_aliases");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<int>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hit_count");

                    b.Property<string>("InputQuery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("input_query");

                    b.Property<DateTime>("LastAccessedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_utc");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("query_hash");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_name_alias_cache_expires");

                    b.HasIndex("HitCount")
                        .HasDatabaseName("ix_name_alias_cache_hit_count");

                    b.HasIndex("LastAccessedUtc")
                        .HasDatabaseName("ix_name_alias_cache_last_accessed");

                    b.HasIndex("InputQuery", "Locale")
                        .HasDatabaseName("ix_name_alias_cache_active");

                    b.HasIndex("QueryHash", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_name_alias_cache_hash_locale");

                    b.ToTable("name_alias_cache", (string)null);
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.NicknameMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.Property<decimal>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsBidirectional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_bidirectional");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nickname");

                    b.Property<string>("NormalizedCanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_canonical_name");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_nickname");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Confidence")
                        .HasDatabaseName("ix_nickname_maps_confidence");

                    b.HasIndex("Locale")
                        .HasDatabaseName("ix_nickname_maps_locale");

                    b.HasIndex("NormalizedCanonicalName")
                        .HasDatabaseName("ix_nickname_maps_canonical_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedCanonicalName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedCanonicalName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NormalizedNickname")
                        .HasDatabaseName("ix_nickname_maps_nickname_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedNickname"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedNickname"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NormalizedCanonicalName", "Locale")
                        .HasDatabaseName("ix_nickname_maps_canonical_name_locale");

                    b.HasIndex("NormalizedNickname", "Locale")
                        .HasDatabaseName("ix_nickname_maps_nickname_locale");

                    b.HasIndex("CanonicalName", "Nickname", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_nickname_maps_unique");

                    b.ToTable("nickname_maps", (string)null);
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternateDoubleMetaphone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dm_alternate");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county");

                    b.Property<int>("CountyId")
                        .HasColumnType("integer")
                        .HasColumnName("county_id");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("county_name");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<char>("Flag")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("flag");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("PartitionHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("dm_hash")
                        .HasComputedColumnSql("ABS(HASHTEXT(normalized_name)) % 64", true);

                    b.Property<string>("PrimaryDoubleMetaphone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dm_primary");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.HasIndex("AlternateDoubleMetaphone")
                        .HasDatabaseName("ix_person_dm_alternate")
                        .HasFilter("dm_alternate IS NOT NULL");

                    b.HasIndex("CountyId")
                        .HasDatabaseName("ix_person_county_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_external_id");

                    b.HasIndex("Flag")
                        .HasDatabaseName("ix_person_flag");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_person_normalized_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PrimaryDoubleMetaphone")
                        .HasDatabaseName("ix_person_dm_primary")
                        .HasFilter("dm_primary IS NOT NULL");

                    b.HasIndex("CountyId", "Flag")
                        .HasDatabaseName("ix_person_county_flag");

                    b.ToTable("person", null, t =>
                        {
                            t.HasComment("Person table partitioned by dm_hash for better performance");
                        });

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.PersonName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BeiderMorseCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bm_code");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DoubleMetaphoneCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dm_code");

                    b.Property<DateTime?>("LastEnrichmentUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enrichment_utc");

                    b.Property<string>("LocaleHint")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale_hint");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ScriptHint")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("script_hint");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.HasIndex("BeiderMorseCode")
                        .HasDatabaseName("ix_person_names_bm_code")
                        .HasFilter("bm_code IS NOT NULL");

                    b.HasIndex("CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_person_names_canonical_name");

                    b.HasIndex("DoubleMetaphoneCode")
                        .HasDatabaseName("ix_person_names_dm_code")
                        .HasFilter("dm_code IS NOT NULL");

                    b.HasIndex("LastEnrichmentUtc")
                        .HasDatabaseName("ix_person_names_last_enrichment")
                        .HasFilter("last_enrichment_utc IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_person_names_normalized_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LocaleHint", "ScriptHint")
                        .HasDatabaseName("ix_person_names_locale_script");

                    b.ToTable("person_names", (string)null);
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.BeiderMorseVariant", b =>
                {
                    b.HasOne("PhoneticAnalyzers.Domain.Entities.Person", null)
                        .WithMany("BeiderMorseVariants")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.NameAlias", b =>
                {
                    b.HasOne("PhoneticAnalyzers.Domain.Entities.PersonName", "PersonName")
                        .WithMany("Aliases")
                        .HasForeignKey("PersonNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonName");
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.Person", b =>
                {
                    b.Navigation("BeiderMorseVariants");
                });

            modelBuilder.Entity("PhoneticAnalyzers.Domain.Entities.PersonName", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
