namespace PhoneticAnalyzers.Domain.Enums;

/// <summary>
/// Represents the type of name alias for multilingual search
/// </summary>
public enum AliasType
{
    /// <summary>
    /// A common nickname (e.g., Liz for Elizabeth)
    /// </summary>
    Nickname,

    /// <summary>
    /// A diminutive form (e.g., Johnny for Jonathan)
    /// </summary>
    Diminutive,

    /// <summary>
    /// An anglicization of a foreign name
    /// </summary>
    Anglicization,

    /// <summary>
    /// A transliteration to Latin script
    /// </summary>
    Transliteration,

    /// <summary>
    /// Alternative spelling variant
    /// </summary>
    Spelling,

    /// <summary>
    /// Abbreviation (e.g., St for Saint)
    /// </summary>
    Abbreviation,

    /// <summary>
    /// Cultural or regional variant
    /// </summary>
    Cultural,

    /// <summary>
    /// LLM-generated variant
    /// </summary>
    LlmGenerated
}

/// <summary>
/// Represents the source of a name alias
/// </summary>
public enum AliasSource
{
    /// <summary>
    /// Manually curated nickname map
    /// </summary>
    Curated,

    /// <summary>
    /// Rule-based expansion
    /// </summary>
    Rule,

    /// <summary>
    /// Generated by Language Model
    /// </summary>
    Llm,

    /// <summary>
    /// User-provided alias
    /// </summary>
    User
}